[project]
name = "uv-web-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "concurrent-log-handler>=0.9.28",
    "flask>=3.1.2",
    "gunicorn>=23.0.0",
    "requests>=2.32.5",
]
